# Generated by Django 3.2.9 on 2021-11-09 11:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "date_created",
                    models.DateTimeField(
                        auto_created=True, help_text="YYYY-MM-DDThh:mm<TZDSuffix>"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.CharField(blank=True, default="", max_length=140)),
                ("phone_number", models.CharField(max_length=12)),
                (
                    "sent",
                    models.BooleanField(
                        default=False,
                        help_text="has the message been sent successfully",
                    ),
                ),
                (
                    "delivered",
                    models.BooleanField(
                        default=False,
                        help_text="has the message been delivered successfully",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[("plug", "provider Plug"), ("file", "provider File")],
                        default="plug",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
